name: 🔑 Daily AoC Token Check
description: Checks whether the AoC Token, configured in github secrets, has not yet expired.
run-name: >
  ${{ github.event_name == 'workflow_dispatch'
      && format('🔑 AoC Token Check (manual) - %Y-%m-%d %H:%M:%S', now())
      || format('🔑 AoC Token Check (daily) - %Y-%m-%d', now()) }}


on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  check-token:
    runs-on: ubuntu-slim
    steps:
      - name: Check AoC session token
        env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}
        run: |
          URL="https://adventofcode.com/2015/day/4/input"

          if [[ -z "$AOC_SESSION" ]]; then
              echo "ERROR: AOC_SESSION token not provided." >&2
              exit 1
          fi

          status=$(curl -s -o /dev/null -w "%{http_code}" \
              --cookie "session=$AOC_SESSION" "$URL")

          if [[ $status == 200 ]]; then
              echo "OK"
              exit 0
          else
              echo "NOT OK (status $status)"
              exit 2
          fi